In [1]:
from example.inference import load_models, prediction

/home/user/anaconda3/envs/sufia/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model, tokenizer = load_models("saiful9379/Bangla_GPT2")

2023-03-07 23:08:07.743094: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-07 23:08:07.748949: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-07 23:08:07.749695: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-07 23:08:07.750917: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

In [3]:
text = ["গাজীপুরের কালিয়াকৈর উপজেলার তেলিরচালা"]
p_text = prediction(text[0], model, tokenizer )

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to 2 (first `eos_token_id`) to generate sequence


tf.Tensor(
[[208 172 211 197 200 186 174 173 174 185 172 183 176 178 225 180 275 174
  750 173 183 172 174 207 173 183 176 434 172 183 172]], shape=(1, 31), dtype=int32)


In [4]:
print(p_text)

গাজীপুরের কালিয়াকৈর উপজেলার তেলিরচালা গ্রামে অবস্থিত বিদ্যালয়ের প্রধান শিক্ষক আবদুল হাই বাচ্চুকে গৃহবন্দী করে রাখা হয়েছে এবং তিনি তাঁর ব্যক্তিগত কোনো সম্পর্ক ছাড়তে না দেওয়ায় এলাকাবাসীর উদ্বেগ-উৎকণ্ঠা বেড়েই চলেছে। বৃহস্পতি
বিএনপির নেতৃত


In [5]:
text = "বহুল আলোচিত দশম জাতীয় সংসদ"
p_text = prediction(text[0], model, tokenizer )

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to 2 (first `eos_token_id`) to generate sequence


tf.Tensor([[182]], shape=(1, 1), dtype=int32)


In [6]:
p_text

'বাচন কমিশনের সাংবিধানিক দায়িত্ব। কিন্তু দুর্ভাগ্যজনকভাবে তারা সেটি করতে পারছে না। প্রথম আলো: আপনাকে ধন্যবাদ। ড. কামাল হোসেন l এই সংকট নিরসনে জাতিসংঘসহ বিদেশি বন্ধুপ্রতিম রাষ্ট্রগুলোর সঙ্গে আলাপ-আলোচনা করে আমরা একটি সমঝোতা চাই। এই ব্যবস্থা পুনরুজ্জীবনে আম'

In [7]:
from transformers import TFGPT2LMHeadModel, GPT2Tokenizer

tokenizer =  GPT2Tokenizer.from_pretrained("saiful9379/Bangla_GPT2")

model = TFGPT2LMHeadModel.from_pretrained("saiful9379/Bangla_GPT2")
text = "বহুল আলোচিত দশম জাতীয় সংসদ"
input_ids = tokenizer.encode(text, return_tensors='tf')

print(input_ids)


output = model.generate(
        input_ids,
        max_length=175,
        num_beams=10,
        temperature=0.7,
        no_repeat_ngram_size=2,
        num_return_sequences=5
    )
predicted_text = tokenizer.decode(output[0], skip_special_tokens=True)
print(predicted_text)

All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at saiful9379/Bangla_GPT2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to 2 (first `eos_token_id`) to generate sequence


tf.Tensor([[590 186 183 304 191 215 176 179 782 222 172 179 197 170 166 187 219 436]], shape=(1, 18), dtype=int32)
বহুল আলোচিত দশম জাতীয় সংসদ নির্বাচনের তফসিল ঘোষণার পর থেকে এ পর্যন্ত বিভিন্ন স্থানে সহিংসতা ও নাশকতা বেড়ে গেছে। সাম্প্রতিক কালে রাজশাহী. খুলনা. বরিশালসহ অন্য সিটি করপোরেশনে যেসব নেতা-কর্মী গুরুতর অপরাধে মামলা দিচ্ছেন. তাঁরা ক্ষমতাসীন দল ও আইনশৃঙ্খলা রক্ষাকা
