# Import Libraries

In [1]:
# !pip install transformers
# !pip install tokenizer
# !pip install gensim
# !pip install tensorflow-gpu==2.6.0
# !pip install numpy==1.20.0
# !pip install gensim==3.8.3

In [2]:
import os
import tensorflow as tf
from pathlib import Path
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.decoders import ByteLevel as ByteLevelDecoder
from tokenizers.normalizers import NFD, NFKC,Sequence
from tokenizers.trainers import BpeTrainer
from tokenizers.pre_tokenizers import ByteLevel
from transformers import GPT2Tokenizer, GPT2Config, TFGPT2LMHeadModel
from transformers import WEIGHTS_NAME, CONFIG_NAME

/home/user/anaconda3/envs/sufia/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Dataset path
This dataset is prothom alo new data. it containt's 8168 articles.

In [3]:
data_path = "ja/opnion_text_512.txt"
tokenizer_save_path = "tokenizer_voc"
save_model = "bangla_gpt2"
os.makedirs(tokenizer_save_path, exist_ok= True)
os.makedirs(save_model, exist_ok= True)

# Build BPE Tokenizer

In [4]:
def tokenizer_func(text: str, token_min_len: int, token_max_len: int, lower: bool) -> list:
    return [token for token in text.split() if token_min_len <= len(token) <= token_max_len]

## Train Tokenizer

In [5]:
def train_bpe_tokenizer(data_path:str="", tokenizer_save_path:str="")->None:
    tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
    tokenizer.normalizer = Sequence([NFKC()])
    tokenizer.pre_tokenizer = ByteLevel()
    tokenizer.decoder = ByteLevelDecoder()

    trainer = BpeTrainer(
        vocab_size=50000, 
        show_progress=True,
        inital_alphabet=ByteLevel.alphabet(),
        special_tokens=["<s>", "<pad>", "</s>", "<unk>", "<mask>"]
    )
    tokenizer.train(files=[data_path], trainer=trainer)
    tokenizer.model.save(tokenizer_save_path)

In [6]:
train_bpe_tokenizer(data_path=data_path, tokenizer_save_path=tokenizer_save_path)

Ignored unknown kwargs option inital_alphabet





In [7]:
 with open(data_path, "r", encoding='utf-8') as f:
    x = f.read().split("\n")
print(x[0])

বহুল আলোচিত দশম জাতীয় সংসদ নির্বাচন অনুষ্ঠিত হতে আর মাত্র কটা দিন বাকি। নির্বাচনের প্রধান ও আলোচিত রাজনৈতিক দল আওয়ামী লীগ নির্বাচনের মাত্র এক সপ্তাহ আগে তাদের নির্বাচনী ইশতেহার ঘোষণা করেছে। ৫০ পৃষ্ঠাসংবলিত এবারের ইশতেহারে ‘সংখ্যালঘু. ক্ষুদ্র জাতিসত্তা. অনুন্নত সম্প্রদায় ও পার্বত্য চট্টগ্রাম’ শিরোনামে (২২.১ ও ২২.২ ধারায়) কিছু গতানুগতিক প্রতিশ্রুতি প্রদান করা হয়েছে। অন্যদিকে. নির্বাচন কমিশনের আরোপিত প্রয়োজনীয় শর্তাবলি পূরণ করতে না পারায় পার্বত্য চট্টগ্রামের আঞ্চলিক দলগুলোকে নির্বাচন কমিশন থেকে নিবন্ধন দেওয়া হ


In [8]:
tokenizer = GPT2Tokenizer.from_pretrained(tokenizer_save_path,  unk_token="[UNK]")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


# Train Tokenizer test

In [9]:
text = "গাজীপুরের কালিয়াকৈর উপজেলার তেলিরচালা এলাকায় আজ বৃহস্পতিবার রাতের টিফিন খেয়ে একটি পোশাক কারখানার ৫০০ শ্রমিক অসুস্থ হয়ে পড়েছেন।"
input_ids = tokenizer.encode(text, return_tensors='tf')

2023-02-26 23:32:54.200787: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-26 23:32:54.219350: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-26 23:32:54.219661: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-26 23:32:54.221067: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

In [10]:
input_ids

<tf.Tensor: shape=(1, 94), dtype=int32, numpy=
array([[ 208,  172,  211,  197,  200,  186,  174,  173,  174,  185,  172,
         183,  176,  178,  225,  180,  275,  174,  750,  173,  183,  172,
         174,  207,  173,  183,  176,  434,  172,  183,  172,  475,  172,
         180,  172,  178,  181,  517,  188,  247,  698,  175,  344,  176,
         182,  172,  174,  228,  172,  179,  173,  174,  290,  176,  272,
         176,  177,  262,  173,  178,  210,  286,  176,  190,  191,  198,
         172,  180,  185,  172,  790,  172,  177,  172,  174, 1530,  229,
         175,  310,  176,  180,  381,  186,  194,  175,  217,  234,  210,
         350,  210,  203,  173,  177,  193]], dtype=int32)>

In [11]:
string_tokenized = tokenizer.encode(text)
print(string_tokenized)

[208, 172, 211, 197, 200, 186, 174, 173, 174, 185, 172, 183, 176, 178, 225, 180, 275, 174, 750, 173, 183, 172, 174, 207, 173, 183, 176, 434, 172, 183, 172, 475, 172, 180, 172, 178, 181, 517, 188, 247, 698, 175, 344, 176, 182, 172, 174, 228, 172, 179, 173, 174, 290, 176, 272, 176, 177, 262, 173, 178, 210, 286, 176, 190, 191, 198, 172, 180, 185, 172, 790, 172, 177, 172, 174, 1530, 229, 175, 310, 176, 180, 381, 186, 194, 175, 217, 234, 210, 350, 210, 203, 173, 177, 193]


In [13]:
token_list = [tokenizer.decode(i) for i in string_tokenized]
print(token_list)

['গ', 'া', 'জ', 'ী', 'প', 'ু', 'র', 'ে', 'র', ' ক', 'া', 'ল', 'ি', 'য', '়া', 'ক', 'ৈ', 'র', ' উপজ', 'ে', 'ল', 'া', 'র', ' ত', 'ে', 'ল', 'ি', 'রচ', 'া', 'ল', 'া', ' এল', 'া', 'ক', 'া', 'য', '়', ' আজ', ' ব', 'ৃ', 'হস', '্', 'পত', 'ি', 'ব', 'া', 'র', ' র', 'া', 'ত', 'ে', 'র', ' ট', 'ি', 'ফ', 'ি', 'ন', ' খ', 'ে', 'য', '়ে', ' একট', 'ি', ' প', 'ো', 'শ', 'া', 'ক', ' ক', 'া', 'রখ', 'া', 'ন', 'া', 'র', ' ৫০০', ' শ', '্', 'রম', 'ি', 'ক', ' অস', 'ু', 'স', '্', 'থ', ' হয', '়ে', ' পড', '়ে', 'ছ', 'ে', 'ন', '।']


# Train GPT2

In [14]:
tokenizer.add_special_tokens({
    "eos_token": "</s>",
    "bos_token": "<s>",
    "unk_token": "<unk>",
    "pad_token": "<pad>",
    "mask_token": "<mask>"
})

0

In [15]:
config = GPT2Config(
    vocab_size=tokenizer.vocab_size,
    bos_token_id=tokenizer.bos_token_id,
    eos_token_id=tokenizer.eos_token_id
)

In [16]:
model = TFGPT2LMHeadModel(config)

2023-02-26 23:33:08.306529: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.


In [20]:
paths = [data_path]
single_string = ''
for filename in paths:
    with open(filename, "r", encoding='utf-8') as f:
        x = f.read()
    single_string += x + tokenizer.eos_token

string_tokenized = tokenizer.encode(single_string)
print("Done tokenizing")

Done tokenizing


In [24]:
examples = []
block_size = 200
BATCH_SIZE = 12
BUFFER_SIZE = 1000
for i in range(0, len(string_tokenized) - block_size + 1, block_size):
#     print(string_tokenized[i:i + block_size])
    examples.append(string_tokenized[i:i + block_size])
inputs, labels = [], []

for ex in examples:
    inputs.append(ex[:-1])
    labels.append(ex[1:])

dataset = tf.data.Dataset.from_tensor_slices((inputs, labels))
dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)
print("Done creating dataset")

Done creating dataset


In [25]:
optimizer = tf.keras.optimizers.Adam(
    learning_rate=3e-5, epsilon=1e-08, clipnorm=1.0)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
model.compile(optimizer=optimizer, loss=[
              loss, *[None] * model.config.n_layer], metrics=[metric])

In [26]:
num_epoch = 100
history = model.fit(dataset, epochs=num_epoch, verbose=1)

Epoch 1/100
24345/24345 [==============================] - 3354s 138ms/step - loss: 2.1462 - accuracy: 0.5140
Epoch 2/100
24345/24345 [==============================] - 3333s 137ms/step - loss: 1.6476 - accuracy: 0.6100
Epoch 3/100
24345/24345 [==============================] - 3337s 137ms/step - loss: 1.5232 - accuracy: 0.6353
Epoch 4/100
24345/24345 [==============================] - 3333s 137ms/step - loss: 1.4511 - accuracy: 0.6500
Epoch 5/100
24345/24345 [==============================] - 3332s 137ms/step - loss: 1.4006 - accuracy: 0.6602
Epoch 6/100
24345/24345 [==============================] - 3329s 137ms/step - loss: 1.3618 - accuracy: 0.6680
Epoch 7/100
24345/24345 [==============================] - 3334s 137ms/step - loss: 1.3303 - accuracy: 0.6743
Epoch 8/100
24345/24345 [==============================] - 3333s 137ms/step - loss: 1.3036 - accuracy: 0.6796
Epoch 9/100
24345/24345 [==============================] - 3440s 141ms/step - loss: 1.2802 - accuracy: 0.6842
Epoch 10/1

KeyboardInterrupt: 

In [27]:
save_path = './gpt2_bangla'
if not os.path.exists(save_path):
    os.makedirs(save_path)

model_to_save = model.module if hasattr(model, 'module') else model
output_model_file = os.path.join(save_path, WEIGHTS_NAME)
output_config_file = os.path.join(save_path, CONFIG_NAME)

model.save_pretrained(save_path)
model_to_save.config.to_json_file(output_config_file)

# save tokenizer
tokenizer.save_pretrained(save_path)

('./gpt2_bangla/tokenizer_config.json',
 './gpt2_bangla/special_tokens_map.json',
 './gpt2_bangla/vocab.json',
 './gpt2_bangla/merges.txt',
 './gpt2_bangla/added_tokens.json')

# Prediction

In [28]:
from transformers import TFGPT2LMHeadModel, GPT2Tokenizer
output_dir = "./gpt2_bangla"
tokenizer = GPT2Tokenizer.from_pretrained(output_dir)
model = TFGPT2LMHeadModel.from_pretrained(output_dir)

All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at ./gpt2_bangla.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [50]:
# text ="বহুল আলোচিত দশম জাতীয় সংসদ নির্বাচন অনুষ্ঠিত হতে আর মাত্র কটা দিন বাকি।"
text = "বহুল আলোচিত দশম জাতীয় সংসদ"
input_ids = tokenizer.encode(text, return_tensors='tf')

In [51]:
input_ids

<tf.Tensor: shape=(1, 18), dtype=int32, numpy=
array([[590, 186, 183, 304, 191, 215, 176, 179, 782, 222, 172, 179, 197,
        170, 166, 187, 219, 436]], dtype=int32)>

In [52]:
print(tokenizer.decode(input_ids[0], skip_special_tokens=True))

বহুল আলোচিত দশম জাতীয় সংসদ


In [72]:
beam_output = model.generate(
    input_ids,
    max_length=175,
    num_beams=10,
    temperature=0.7,
    no_repeat_ngram_size=2,
    num_return_sequences=5
)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to 2 (first `eos_token_id`) to generate sequence


In [73]:
# beam_output

In [74]:
print(tokenizer.decode(beam_output[0], skip_special_tokens=True))

বহুল আলোচিত দশম জাতীয় সংসদ নির্বাচনের তফসিল ঘোষণার পর থেকে এ পর্যন্ত বিভিন্ন স্থানে সহিংসতা ও নাশকতা বেড়ে গেছে। সাম্প্রতিক কালে রাজশাহী. খুলনা. বরিশালসহ অন্য সিটি করপোরেশনে যেসব নেতা-কর্মী গুরুতর অপরাধে মামলা দিচ্ছেন. তাঁরা ক্ষমতাসীন দল ও আইনশৃঙ্খলা রক্ষাকা
